### PR TITLE
New York Times - Clone

### PR DESCRIPTION
**Pull request by jstloyal**
#### What does this PR do?

- Shows how to position and float elements

### Description of Task to be completed?

 - Added the HTML index file
 - Added CSS to style and position the element. 
 - Ran validations on our Html and CSS. 

#### How should this be manually tested? 

- Clone this branch. 
- open the index.html file on your browser 

#### Screenshot 

Screenshot_2020-03-05 New York Times

### CODE REVIEW

**Comment by majovanilla** [comment]
### Code Review in progress :eyes:  by Maria Reyes

**Comment by majovanilla** [comment]
Hey team, 👋

## You did a *great* job on this project! 💜 

- Good Readme template
- Excellent Pull Request Message
- Great work with the page!!

There are still some changes 👇 you need to implement to approve this request 🔍

### Required Changes: ✍️

- Always remember to check your HTML using the [validator](https://validator.w3.org/). You have some warnings. Please fix them. In this case, is about the use of a section without a heading. It's not like you need to create a fake heading, but to choose a different tag if you won't include one.
Screenshot from 2020-03-04 12-30-07

- Improve your Readme file. It should be more descriptive of the project: what you did, how you did it, what was the purpose of the project... You are using a great template!.

- You don't need to copy the advertisement in your clone. Please delete them. It will make your page look much cleaner.

- Fix your navbar. Check on the original page and see how the positioned the elements: two buttons at the far right side, the NYT logo in the center and the hamburger and search buttons to the left.

- Center all the elements in your page: the bottom section should be aligned with the rest of the elements.

- Check the width of your two large images: it's a little bit larger than the original page, making it look disproportioned (the first one). Please fix it.

- Make the comment button at the end to look like the original page.
yours: 
Screenshot from 2020-03-04 12-40-41

original:
Screenshot from 2020-03-04 12-41-06

- Take a look at the bottom section and work with the general width and each element's width. Also, change the font-weight (it shouldn't be bold) Everything should look like the original page.

Yours:
Screenshot from 2020-03-04 12-43-37

Original:
Screenshot from 2020-03-04 12-43-44

- The footer should be fixed at the bottom.

### Optional Changes:

If you want to make your project even better 🔥💥, I have a few suggestions you can implement.  

These are completely [Optional]: 🦔

- Consider implementing the hover style to all the links on the page.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Review by rOluochKe — CHANGES_REQUESTED** [review]
Hello Team,
### You have done well so far :clap: for also making changes from previous reviews. However, there are a few issues to work on before your project could be approved.
- Most of your images are not well defined, they are squeezed, you can define a with and height to achieve this 
images 2
images
- Also, unwanted files like .vscode can be added in a .gitignore file as they are not required

### Make these changes and resubmit for another review. Good luck.
- For assistance, contact me on slack @iamraymond
- Happy coding!

**Review by mosesogwo — CHANGES_REQUESTED** [review]
**HI @jstloyal, you are doing great :clap: but the images pointed out in the previous review haven't been fixed.**

You have given the sections with those images - **More in Space and Astronomy** and **The theory of inflation** - a smaller width than they have in the original site. This may be contributing to how the images appear. Compare the width of those sections with the original and make them similar. Ensure that image width and heights are just like it is on the original page.

_**Kindly attend to the above and submit another code review request.**_

**Any question? You can reach me on Slack (Moses Ogwo)**

**Cheers:stars:**

### Status: Changes Requested.

**Comment by lekegitrepo** [comment]
### This PR is under Reviewed by [TSE] _Temitayo Adeleke_

**Comment by lekegitrepo** [comment]
### Well done team 👏 👏 
You have improved the page. However, the "The theory of inflation" section is still not as required by the previous TSE.

**_This is your page:_**

image

**_This is how it looks when I made some adjustment on the page:_**

image

**_Basically, you just need to reduce the margin-left and margin-right of the inflation class in your CSS rule._**

**_Make this adjustment and resubmit for review._**

If you have any doubt or question contact me on slack.

### Reviewed by: _Temitayo Adeleke_

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
### Status: Required Changes

**Comment by majovanilla** [comment]
Good job team!! :medal_military: 

You are almost there!! :muscle: :clap: 

Please just make the last section to look like the original page. This was an earlier requirement that you didn't complete. This should be the last thing before approving your project.

Your page looks like this:
Screenshot from 2020-03-06 04-29-28

And it should look like this;
Screenshot from 2020-03-06 04-33-03

The reason is the same as the above review: you are using a margin-left and right to center it. The best way to center an element horizontally is by using `margin: auto`. In your project, you could change that in the class `main-grid` and then adjust the width to be around 70% Just make sure yo also change the separator and the  Editor's pick title.


## Please, make all REQUIRED changes and submit your request again! 😀

If you have any questions, feel free to send me a message through Slack (@majo)
I would be happy to help! 👩‍💻 


Happy coding 🤓

--Maria Reyes

**Comment by uryelah** [comment]
Hello **Loyalty Adetayo** & **Frank Okiror**, I'm Sarah, your reviewer for this PR 👩‍🚀  

**Good work fixing the size of most images as required by the last review, you did well!✨ 🌟 **
Hang in there because there's still a fix needed to make this project even more awesome.

---------    

**Great job at: 🥇** 
- making an outstanding PR message
- using icons
- using semantic HTML
- making a great footer
- styling your text well
- the fixed-footer looks amazing 🔥 

**You still need to fix the issues below before you can move to the next project**

---------

### Required changes 🛠 

- [ ] Your 'Editor Picks' images look to have different sizes. Please make them the same size.
Screenshot_2020-03-06 New York Times
**Important:**
After closer inspection it looks like you are saving screencaps of the images instead of just saving them, that's why the sizes look weird and the captions are in the images.
Please don't do that, to save an image from a site you can simply click with a right button over it and choose to 'save image'.
**Taking screencaps of images will get you images of inconsistent size and lower quality. Avoid that.**

- [ ] Add the image captions as text.

- [ ] The original page 'More in Space and Astronomy' and 'Editor Picks' areas are close, while yours have a bigger margin between them. Please fix that spacing.

**Original:**
Screenshot_2020-03-06 Space Ripples Reveal Big Bang’s Smoking Gun

**Your version:**
Screenshot_2020-03-06 New York Times(1)

---------
 
**Please fix the required changes 👷  before asking for a new code review**

---------

Cheers and Happy coding!👏👏👏

Code review by **Sarah Uryelah Silva Chamorro**

(Feel free to contact me on slack by the handle of  **sarah** if you have any additional question)

**Comment by SofiBretz** [comment]
### Well done Team 👏

**Project Approved!**

You did all the changes required previously. 
Good Luck with your next project. Happy coding!

**You can merge 👍**

SofiBretz.

**Pull request merged**
